<?php

/*
 * This file is part of the P8P project.
 *
 * (c) Julien Jacottet <jjacottet@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace P8p\Client\Tests\Attribute;

use P8p\Client\Attribute\K8sCustomResourceSchema;
use PHPUnit\Framework\TestCase;

class K8sCustomResourceSchemaTest extends TestCase
{
    public function testConstructorWithAllParameters(): void
    {
        $schema = new K8sCustomResourceSchema(
            kind: 'MyResource',
            group: 'example.com',
            version: 'v1',
            plural: 'myresources',
            namespaced: true,
            singular: 'myresource',
            shortName: 'mr',
        );

        $this->assertSame('MyResource', $schema->kind);
        $this->assertSame('example.com', $schema->group);
        $this->assertSame('v1', $schema->version);
        $this->assertSame('myresources', $schema->plural);
        $this->assertTrue($schema->namespaced);
        $this->assertSame('myresource', $schema->singular);
        $this->assertSame('mr', $schema->shortName);
    }

    public function testConstructorWithMinimalParameters(): void
    {
        $schema = new K8sCustomResourceSchema(
            kind: 'TestResource',
            group: 'test.io',
            version: 'v1beta1',
            plural: 'testresources',
        );

        $this->assertSame('TestResource', $schema->kind);
        $this->assertSame('test.io', $schema->group);
        $this->assertSame('v1beta1', $schema->version);
        $this->assertSame('testresources', $schema->plural);
        $this->assertTrue($schema->namespaced); // Default value
        $this->assertSame('testresource', $schema->singular); // Auto-generated from kind
        $this->assertNull($schema->shortName);
    }

    public function testSingularAutoGeneratedFromKind(): void
    {
        $schema = new K8sCustomResourceSchema(
            kind: 'CronJob',
            group: 'batch',
            version: 'v1',
            plural: 'cronjobs',
        );

        $this->assertSame('cronjob', $schema->singular);
    }

    public function testClusterScopedResource(): void
    {
        $schema = new K8sCustomResourceSchema(
            kind: 'ClusterResource',
            group: 'cluster.io',
            version: 'v1',
            plural: 'clusterresources',
            namespaced: false,
        );

        $this->assertFalse($schema->namespaced);
    }

    public function testGetNameReturnsCorrectFormat(): void
    {
        $schema = new K8sCustomResourceSchema(
            kind: 'MyResource',
            group: 'example.com',
            version: 'v1',
            plural: 'myresources',
        );

        $this->assertSame('myresources.example.com', $schema->getName());
    }

    public function testGetNameWithDifferentGroup(): void
    {
        $schema = new K8sCustomResourceSchema(
            kind: 'Database',
            group: 'databases.acme.io',
            version: 'v1alpha1',
            plural: 'databases',
        );

        $this->assertSame('databases.databases.acme.io', $schema->getName());
    }

    public function testGetScopeReturnsNamespacedForNamespacedResource(): void
    {
        $schema = new K8sCustomResourceSchema(
            kind: 'MyResource',
            group: 'example.com',
            version: 'v1',
            plural: 'myresources',
            namespaced: true,
        );

        $this->assertSame('Namespaced', $schema->getScope());
    }

    public function testGetScopeReturnsClusterForClusterScopedResource(): void
    {
        $schema = new K8sCustomResourceSchema(
            kind: 'ClusterResource',
            group: 'cluster.io',
            version: 'v1',
            plural: 'clusterresources',
            namespaced: false,
        );

        $this->assertSame('Cluster', $schema->getScope());
    }

    public function testGetApiVersionInheritsFromParent(): void
    {
        $schema = new K8sCustomResourceSchema(
            kind: 'MyResource',
            group: 'example.com',
            version: 'v1',
            plural: 'myresources',
        );

        $this->assertSame('example.com/v1', $schema->getApiVersion());
    }

    public function testGetApiVersionWithEmptyGroup(): void
    {
        $schema = new K8sCustomResourceSchema(
            kind: 'CoreResource',
            group: '',
            version: 'v1',
            plural: 'coreresources',
        );

        $this->assertSame('v1', $schema->getApiVersion());
    }
}
